spring.application.name=mobileshop

spring.datasource.url=jdbc:mysql://localhost:3306/test2
spring.datasource.username=root
spring.datasource.password=Hoan1904

spring.jpa.generate-ddl=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.signerKey = eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJkZXZ0ZXJpYS5jb20iLCJzdWIiOiJIb2FuMTkwNCIsImV4cCI6MTc3NjIzMTg0MiwiY3VzdG9tQ2xhaW0iOiJDdXN0b20iLCJpYXQiOjE3NzYyMjgyNDJ9.Fc2ChYKoJkg1VSTCAukEEx8baWVQdS5FZkJQM-CGiErMaDnkOyRongxcWYRSYF3ef4CIkpa451xNyNnbclSoDQ
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:Init_DB.sql
spring.sql.init.data-locations=classpath:add_data_db.sql

spring.security.user.name=pbl3
spring.security.user.password=123456
server.port=8080
